[build-system]
requires = [
	"wheel", "setuptools",
	"chardet",
	"lxml",
	"pathspec",
	"tree-sitter",
	"snakeoil @ https://github.com/pkgcore/snakeoil/archive/master.tar.gz#egg=snakeoil",
	"pkgcore @ https://github.com/pkgcore/pkgcore/archive/master.tar.gz#egg=pkgcore",
]
build-backend = "setuptools.build_meta"
